#include "windows_adapter.h"

// Инициализаяция виртуальной таблицы функций
const net_vtable_dispatcher windows_vtable = {
    .bind_net_register                      = windows_net_register,
    .bind_net_activate                      = windows_net_activate,
    .bind_net_is_ready                      = windows_net_is_ready,
    .bind_net_cleanup                       = windows_net_cleanup,
    .bind_net_socket_create                 = windows_net_socket_create,
    .bind_net_socket_close                  = windows_net_socket_close,
    .bind_net_socket_set_options            = windows_net_socket_set_options,
    .bind_net_socket_get_options            = windows_net_socket_get_options,
    .bind_net_socket_bind                   = windows_net_socket_bind,
    .bind_net_socket_connect                = windows_net_socket_connect,
    .bind_net_socket_listen                 = windows_net_socket_listen,
    .bind_net_socket_accept                 = windows_net_socket_accept,
    .bind_net_socket_send                   = windows_net_socket_send,
    .bind_net_socket_send_to                = windows_net_socket_send_to,
    .bind_net_socket_receive                = windows_net_socket_receive,
    .bind_net_socket_receive_from           = windows_net_socket_receive_from,
    .bind_net_address_parse                 = windows_net_address_parse,
    .bind_net_address_to_string             = windows_net_address_to_string,
    .bind_net_socket_get_local_address      = windows_net_socket_get_local_address,
    .bind_net_socket_get_remote_address     = windows_net_socket_get_remote_address,
    .bind_net_socket_set_nonblocking        = windows_net_socket_set_nonblocking,
    .bind_net_socket_can_read               = windows_net_socket_can_read,
    .bind_net_socket_can_write              = windows_net_socket_can_write,
    .bind_net_socket_last_error             = windows_net_socket_last_error,
    .bind_net_socket_last_platform_error    = windows_net_socket_last_platform_error,
};